# Data
label: ['A', 'B']
image_size: 224
num_domains: 1
num_aug_domains: 1

crop: True
jitter: True
noise: True

# PATH
tr_dataset_path: "M:/Side/2024_TourAPI/DB/train.csv"
te_dataset_path: "M:/Side/2024_TourAPI/DB/test.csv"


ckp_path: "M:/Side/2024_TourAPI/backup/resnet101_Keyword/try_3/ckp"
log_path: "M:/Side/2024_TourAPI/backup/resnet101_Keyword/try_3/log"

# Train
model_name: 'resnet101'
cls_num: 123
num_keywords: 17
seed: 1004

epoch: 50
device: "cuda"

lr: 0.00001

batch_size: 8
weight_decay: 0.00001
momentum: 0.9
b1: 0.5
b2: 0.999

do_ckp_save: True
do_ckp_load: False
do_print: True
do_logging: True
